FROM node:20-alpine
EXPOSE 5173
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
CMD ["npm", "run", "dev"]